:- dynamic pokemon/4.

pokemon("slowking", "pink", "waters-edge", "mega-punch").
pokemon("misdreavus", "gray", "cave", "headbutt").
pokemon("murkrow", "black", "forest", "wing-attack").
pokemon("umbreon", "black", "urban", "cut").
pokemon("espeon", "purple", "urban", "cut").
pokemon("quagsire", "blue", "waters-edge", "mega-punch").
pokemon("wooper", "blue", "waters-edge", "ice-punch").
pokemon("yanma", "red", "forest", "wing-attack").
pokemon("sunflora", "yellow", "grassland", "pound").
pokemon("sunkern", "yellow", "grassland", "swords-dance").
pokemon("aipom", "purple", "forest", "double-slap").
pokemon("jumpluff", "blue", "grassland", "swords-dance").
pokemon("hoppip", "pink", "grassland", "pay-day").
pokemon("skiploom", "green", "grassland", "swords-dance").
pokemon("politoed", "green", "waters-edge", "double-slap").
pokemon("sudowoodo", "brown", "forest", "mega-punch").
pokemon("marill", "blue", "waters-edge", "mega-punch").
pokemon("azumarill", "blue", "waters-edge", "mega-punch").
pokemon("ampharos", "yellow", "grassland", "mega-punch").
pokemon("bellossom", "green", "grassland", "swords-dance").
pokemon("flaaffy", "pink", "grassland", "mega-punch").
pokemon("xatu", "green", "forest", "fly").
pokemon("mareep", "white", "grassland", "sand-attack").
pokemon("togetic", "white", "forest", "mega-punch").
pokemon("natu", "green", "forest", "double-edge").
pokemon("togepi", "white", "forest", "mega-punch").
pokemon("igglybuff", "pink", "grassland", "pound").
pokemon("cleffa", "pink", "mountain", "pound").
pokemon("pichu", "yellow", "forest", "double-slap").
pokemon("lanturn", "blue", "sea", "take-down").
pokemon("chinchou", "blue", "sea", "take-down").
pokemon("crobat", "purple", "cave", "wing-attack").
pokemon("ariados", "red", "forest", "swords-dance").
pokemon("spinarak", "green", "forest", "body-slam").
pokemon("ledian", "red", "forest", "comet-punch").
pokemon("ledyba", "red", "forest", "comet-punch").
pokemon("noctowl", "brown", "forest", "fly").
pokemon("hoothoot", "brown", "forest", "wing-attack").
pokemon("furret", "brown", "grassland", "fire-punch").
pokemon("sentret", "brown", "grassland", "fire-punch").
pokemon("feraligatr", "blue", "waters-edge", "mega-punch").
pokemon("croconaw", "blue", "waters-edge", "mega-punch").
pokemon("totodile", "blue", "waters-edge", "mega-punch").
pokemon("typhlosion", "yellow", "grassland", "mega-punch").
pokemon("cyndaquil", "yellow", "grassland", "cut").
pokemon("quilava", "yellow", "grassland", "cut").
pokemon("mew", "pink", "rare", "pound").
pokemon("meganium", "green", "grassland", "swords-dance").
pokemon("bayleef", "green", "grassland", "swords-dance").
pokemon("chikorita", "green", "grassland", "swords-dance").
pokemon("mewtwo", "purple", "rare", "mega-punch").
pokemon("dragonite", "brown", "waters-edge", "fire-punch").
pokemon("dragonair", "blue", "waters-edge", "bind").
pokemon("dratini", "blue", "waters-edge", "bind").
pokemon("zapdos", "yellow", "rare", "razor-wind").
pokemon("moltres", "yellow", "rare", "razor-wind").
pokemon("snorlax", "black", "mountain", "mega-punch").
pokemon("articuno", "blue", "rare", "razor-wind").
pokemon("aerodactyl", "purple", "mountain", "razor-wind").
pokemon("kabutops", "brown", "sea", "scratch").
pokemon("kabuto", "brown", "sea", "scratch").
pokemon("omastar", "blue", "sea", "bind").
pokemon("omanyte", "blue", "sea", "bind").
pokemon("flareon", "red", "urban", "sand-attack").
pokemon("porygon", "pink", "urban", "tackle").
pokemon("jolteon", "yellow", "urban", "double-kick").
pokemon("vaporeon", "blue", "urban", "sand-attack").
pokemon("eevee", "brown", "urban", "sand-attack").
pokemon("lapras", "blue", "sea", "headbutt").
pokemon("gyarados", "blue", "waters-edge", "headbutt").
pokemon("tauros", "brown", "grassland", "stomp").
pokemon("pinsir", "brown", "forest", "vice-grip").
pokemon("ditto", "purple", "urban", "transform").
pokemon("magikarp", "red", "waters-edge", "tackle").
pokemon("jynx", "red", "urban", "pound").
pokemon("electabuzz", "yellow", "grassland", "mega-punch").
pokemon("magmar", "red", "mountain", "mega-punch").
pokemon("mr-mime", "pink", "urban", "pound").
pokemon("scyther", "green", "grassland", "razor-wind").
pokemon("starmie", "purple", "sea", "tackle").
pokemon("staryu", "brown", "sea", "tackle").
pokemon("seaking", "red", "waters-edge", "horn-attack").
pokemon("goldeen", "red", "waters-edge", "horn-attack").
pokemon("kangaskhan", "brown", "grassland", "comet-punch").
pokemon("seadra", "blue", "sea", "headbutt").
pokemon("chansey", "pink", "urban", "pound").
pokemon("horsea", "blue", "sea", "razor-wind").
pokemon("tangela", "blue", "grassland", "swords-dance").
pokemon("rhydon", "gray", "rough-terrain", "mega-punch").
pokemon("rhyhorn", "gray", "rough-terrain", "swords-dance").
pokemon("lickitung", "pink", "grassland", "mega-punch").
pokemon("koffing", "purple", "urban", "tackle").
pokemon("weezing", "purple", "urban", "tackle").
pokemon("hitmonlee", "brown", "urban", "mega-punch").
pokemon("marowak", "brown", "mountain", "mega-punch").
pokemon("hitmonchan", "brown", "urban", "comet-punch").
pokemon("cubone", "brown", "mountain", "mega-punch").
pokemon("exeggcute", "pink", "forest", "swords-dance").
pokemon("exeggutor", "yellow", "forest", "swords-dance").
pokemon("electrode", "red", "urban", "headbutt").
pokemon("kingler", "red", "waters-edge", "vice-grip").
pokemon("krabby", "red", "waters-edge", "vice-grip").
pokemon("voltorb", "red", "urban", "headbutt").
pokemon("hypno", "yellow", "grassland", "pound").
pokemon("drowzee", "yellow", "grassland", "pound").
pokemon("onix", "gray", "cave", "bind").
pokemon("haunter", "purple", "cave", "fire-punch").
pokemon("gengar", "purple", "cave", "mega-punch").
pokemon("gastly", "purple", "cave", "fire-punch").
pokemon("shellder", "purple", "sea", "tackle").
pokemon("muk", "purple", "urban", "pound").
pokemon("cloyster", "purple", "sea", "take-down").
pokemon("grimer", "purple", "urban", "pound").
pokemon("dewgong", "white", "sea", "pay-day").
pokemon("seel", "white", "sea", "pay-day").
pokemon("dodrio", "brown", "grassland", "swords-dance").
pokemon("farfetchd", "brown", "grassland", "razor-wind").
pokemon("doduo", "brown", "grassland", "swords-dance").
pokemon("magneton", "gray", "rough-terrain", "tackle").
pokemon("magnemite", "gray", "rough-terrain", "tackle").
pokemon("slowbro", "pink", "waters-edge", "mega-punch").
pokemon("slowpoke", "pink", "waters-edge", "pay-day").
pokemon("ponyta", "yellow", "grassland", "stomp").
pokemon("rapidash", "yellow", "grassland", "stomp").
pokemon("golem", "brown", "mountain", "mega-punch").
pokemon("graveler", "brown", "mountain", "mega-punch").
pokemon("geodude", "brown", "mountain", "mega-punch").
pokemon("tentacruel", "blue", "sea", "swords-dance").
pokemon("tentacool", "blue", "sea", "swords-dance").
pokemon("victreebel", "green", "forest", "swords-dance").
pokemon("weepinbell", "green", "forest", "swords-dance").
pokemon("bellsprout", "green", "forest", "swords-dance").
pokemon("machamp", "gray", "mountain", "karate-chop").
pokemon("machop", "gray", "mountain", "karate-chop").
pokemon("machoke", "gray", "mountain", "karate-chop").
pokemon("alakazam", "brown", "urban", "mega-punch").
pokemon("kadabra", "brown", "urban", "mega-punch").
pokemon("abra", "brown", "urban", "mega-punch").
pokemon("poliwhirl", "blue", "waters-edge", "double-slap").
pokemon("poliwrath", "blue", "waters-edge", "double-slap").
pokemon("primeape", "brown", "mountain", "karate-chop").
pokemon("growlithe", "brown", "grassland", "double-kick").
pokemon("mankey", "brown", "mountain", "karate-chop").
pokemon("poliwag", "blue", "waters-edge", "double-slap").
pokemon("golduck", "blue", "waters-edge", "mega-punch").
pokemon("arcanine", "brown", "grassland", "headbutt").
pokemon("psyduck", "yellow", "waters-edge", "mega-punch").
pokemon("meowth", "yellow", "urban", "pay-day").
pokemon("persian", "yellow", "urban", "pay-day").
pokemon("dugtrio", "brown", "cave", "scratch").
pokemon("diglett", "brown", "cave", "scratch").
pokemon("venomoth", "purple", "forest", "razor-wind").
pokemon("venonat", "purple", "forest", "tackle").
pokemon("parasect", "red", "forest", "scratch").
pokemon("paras", "red", "forest", "scratch").
pokemon("gloom", "blue", "grassland", "swords-dance").
pokemon("oddish", "blue", "grassland", "swords-dance").
pokemon("vileplume", "red", "grassland", "swords-dance").
pokemon("golbat", "purple", "cave", "razor-wind").
pokemon("wigglytuff", "pink", "grassland", "double-slap").
pokemon("jigglypuff", "pink", "grassland", "pound").
pokemon("zubat", "purple", "cave", "razor-wind").
pokemon("clefairy", "pink", "mountain", "pound").
pokemon("ninetales", "yellow", "grassland", "headbutt").
pokemon("vulpix", "brown", "grassland", "headbutt").
pokemon("clefable", "pink", "mountain", "double-slap").
pokemon("nidoking", "purple", "grassland", "mega-punch").
pokemon("nidorino", "purple", "grassland", "cut").
pokemon("nidoqueen", "blue", "grassland", "mega-punch").
pokemon("nidoran-m", "purple", "grassland", "cut").
pokemon("sandshrew", "yellow", "rough-terrain", "scratch").
pokemon("nidoran-f", "blue", "grassland", "scratch").
pokemon("nidorina", "blue", "grassland", "scratch").
pokemon("sandslash", "yellow", "rough-terrain", "scratch").
pokemon("raichu", "yellow", "forest", "mega-punch").
pokemon("pikachu", "yellow", "forest", "mega-punch").
pokemon("arbok", "purple", "grassland", "bind").
pokemon("spearow", "brown", "rough-terrain", "razor-wind").
pokemon("ekans", "purple", "grassland", "bind").
pokemon("fearow", "brown", "rough-terrain", "razor-wind").
pokemon("rattata", "purple", "grassland", "cut").
pokemon("raticate", "brown", "grassland", "swords-dance").
pokemon("pidgeot", "brown", "forest", "razor-wind").
pokemon("pidgeotto", "brown", "forest", "razor-wind").
pokemon("bulbasaur", "green", "grassland", "razor-wind").
pokemon("squirtle", "blue", "waters-edge", "mega-punch").
pokemon("charmander", "red", "mountain", "mega-punch").
pokemon("charizard", "red", "mountain", "mega-punch").
pokemon("venusaur", "green", "grassland", "swords-dance").
pokemon("blastoise", "blue", "waters-edge", "mega-punch").
pokemon("butterfree", "white", "forest", "razor-wind").
pokemon("charmeleon", "red", "mountain", "mega-punch").
pokemon("ivysaur", "green", "grassland", "swords-dance").
pokemon("wartortle", "blue", "waters-edge", "mega-punch").
pokemon("beedrill", "yellow", "forest", "swords-dance").
pokemon("pidgey", "brown", "forest", "razor-wind").
pokemon("metapod", "green", "forest", "string-shot").
pokemon("kakuna", "yellow", "forest", "string-shot").
pokemon("caterpie", "green", "forest", "tackle").
pokemon("weedle", "brown", "forest", "poison-sting").

